language: node_js
node_js:
- 4.0.0
- 5.8.0
- 6.1.0
after_success: node build_scripts/update_jsdoc.js
deploy:
  provider: npm
  email: franktestrlz@gmail.com
  api_key:
    secure: DuccQp600EzB5b+ixCBbB1NV2XVH7e01UUidrC+PsBI401oFbm9+ktzYmub4cOsU/d+sidHFIdHP4j37HUy00C24icoaP0ygu3aA+uEWGWjY+D/+S8vYub1EQUBwypIp1Exg0+DQwlWQwzcfUlvvmEuJxaM1haxv56W+4KMSygXefa+G/uxTKcnnSBRGSAL+53kY5n0RvVsrKUbmJ23lvI9MfnunRupz/HGbJkUv83yuRQr5u6LTED8nGbQMvmFh37T9Uc83CjxcP6oE8A2PBR3ho8GRSZsbPmoRFVxDtoo1ouphKYLfx0RAxsQtPWYFiymfZuELjaWpa0A5flJQzU1RxgBjNyf/++dMp7lUV+UdTbnyANOO1V2m2sM/+JeBdikglF1ptnTaIQvGam/z/R1RQpR7APBrYm5at6WNbptq6k3x3g7OYcoF2G42OCVQJ/buMqUTNPgAF4TBbcXZidSpmIBy1Dx6+9mlWsc3mPwA0scZEiTtiRCpwq2Z04WfH7t1W6fB+T4Gs5VuOC6z+SV+QsxIsOyvVA9zaDVmVKTEOAmA2SwzFKihrnhOKD3QP9b2vO/jdkXMVlHBeK2ksNq3ZL9PbfSENf5kqysBoMnQ1hcrYZ62o5AqoIjpaInMll6G+EgPYem7PMGiwrBs2QeAu26nXHVnCiBhyZDoNcQ=
  on:
    tags: false
    repo: frankrafael/injectjs
    branch: master
